[build]
builder = "NIXPACKS"
buildCommand = "yarn install && yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production" 